//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddData
{
    using System;
    using System.Collections.Generic;
    
    public partial class cad_block
    {
        public int id { get; set; }
        public string depart_type { get; set; }
        public string block_major { get; set; }
        public string block_size { get; set; }
        public string block_path { get; set; }
        public bool new_block { get; set; }
        public bool valid { get; set; }
    }
}
